{{- if and .Values.healthMonitor.enabled (not .Values.secrets.meshServiceAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toskamesh.fullname" . }}-health-monitor-secrets
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: health-monitor
type: Opaque
stringData:
  {{ default "mesh_service_auth_secret" .Values.secrets.meshServiceAuth.key }}: {{ .Values.global.meshServiceAuthSecret | quote }}
{{- end }}
