<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>ToskaMesh.Runtime.Orleans</PackageId>
    <Title>ToskaMesh Runtime Orleans</Title>
    <Description>Stateful runtime host for ToskaMesh services using Orleans, aligned with MeshLambdaService API.</Description>
    <Authors>ToskaMesh</Authors>
    <RepositoryUrl>https://github.com/abstractivemachines/toska-mesh-cs</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>toska-mesh;runtime;stateful;orleans</PackageTags>
    <Version>0.1.0-preview</Version>
    <PackageReadmeFile>PackageReadme.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="PackageReadme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Core" />
    <PackageReference Include="Microsoft.Orleans.Runtime" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" />
    <PackageReference Include="Microsoft.Orleans.Server" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Consul" />
    <PackageReference Include="OrleansDashboard" />
    <PackageReference Include="Microsoft.Orleans.Reminders.AdoNet" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToskaMesh.Telemetry\ToskaMesh.Telemetry.csproj" />
    <ProjectReference Include="..\ToskaMesh.Security\ToskaMesh.Security.csproj" />
  </ItemGroup>
</Project>
