apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-rpc-demo-config
  labels:
    app.kubernetes.io/name: mesh-rpc-demo
    app.kubernetes.io/instance: mesh-rpc-demo
    app.kubernetes.io/component: example
data:
  Messaging__RabbitMqHost: rabbitmq.toskamesh-infra.svc.cluster.local
  Messaging__RabbitMqVirtualHost: "/"
  # ToskaMesh Service Registration
  Mesh__Service__RegisterAutomatically: "true"
  Mesh__Service__ServiceRegistryProvider: "consul"
  Mesh__Service__Routing__HealthCheckEndpoint: "/health"
  Mesh__ServiceDiscovery__Grpc__Address: "http://toskamesh-discovery.toskamesh.svc.cluster.local:8080"
  Mesh__ServiceDiscovery__Grpc__AllowInsecureTransport: "true"
  Consul__Address: "http://consul-server.toskamesh-infra.svc.cluster.local:8500"
  Mesh__ServiceAuth__Issuer: "ToskaMesh.Services"
  Mesh__ServiceAuth__Audience: "ToskaMesh.Services"
  Mesh__Telemetry__TracingIngest__Enabled: "true"
  Mesh__Telemetry__TracingIngest__Endpoint: "http://toskamesh-tracing-service.toskamesh.svc.cluster.local:8080/api/traces/ingest"
  Mesh__Telemetry__Sampling__Strategy: "ParentBasedAlwaysOn"
  Mesh__Telemetry__Sampling__Ratio: "1"
