apiVersion: v1
kind: Service
metadata:
  name: mesh-rpc-c
  labels:
    app.kubernetes.io/name: mesh-rpc-c
    app.kubernetes.io/instance: mesh-rpc-c
    app.kubernetes.io/component: example
spec:
  selector:
    app.kubernetes.io/name: mesh-rpc-c
    app.kubernetes.io/instance: mesh-rpc-c
    app.kubernetes.io/component: example
  ports:
    - name: http
      port: 8083
      targetPort: 8083
