apiVersion: v1
kind: Service
metadata:
  name: mesh-rpc-a
  labels:
    app.kubernetes.io/name: mesh-rpc-a
    app.kubernetes.io/instance: mesh-rpc-a
    app.kubernetes.io/component: example
spec:
  selector:
    app.kubernetes.io/name: mesh-rpc-a
    app.kubernetes.io/instance: mesh-rpc-a
    app.kubernetes.io/component: example
  ports:
    - name: http
      port: 8081
      targetPort: 8081
