{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "toskamesh.fullname" . }}-gateway-config
  labels:
    {{- include "toskamesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
data:
  consul_address: {{ include "toskamesh.consul.address" . | quote }}
  dashboard_prometheus_url: {{ .Values.gateway.dashboardProxy.prometheusBaseUrl | quote }}
  dashboard_tracing_url: "http://{{ include "toskamesh.fullname" . }}-tracing-service:8080"
  dashboard_discovery_url: "http://{{ include "toskamesh.fullname" . }}-discovery:8080"
  dashboard_healthmonitor_url: "http://{{ include "toskamesh.fullname" . }}-health-monitor:8080"
{{- end }}
